[webserver]
10.10.10.140

[webserver:vars]
ansible_user=alvin
ansible_password=rahasia123
ansible_become_pass=rahasia123 
ansible_connection=ssh
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyCommand="sshpass -p PASSWORD_PROXMOX_KAMU ssh -o StrictHostKeyChecking=no -W %h:%p root@100.72.15.104"'