-- MySQL Script generated by MySQL Workbench
-- Mon Nov 18 22:31:58 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema peduli_panti
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema peduli_panti
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS peduli_panti DEFAULT CHARACTER SET utf8 ;
USE peduli_panti ;

-- -----------------------------------------------------
-- Table peduli_panti.user
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS peduli_panti.user (
  userID INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) NOT NULL,
  email VARCHAR(45) NOT NULL,
  password VARCHAR(45) NOT NULL,
  role VARCHAR(45) NOT NULL,
  image BLOB NULL,
  PRIMARY KEY (userID),
  UNIQUE INDEX email_UNIQUE (email ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table peduli_panti.product
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS peduli_panti.product (
  productID INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) NOT NULL,
  price INT NOT NULL,
  description TEXT NOT NULL,
  PRIMARY KEY (productID))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table peduli_panti.bundle
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS peduli_panti.bundle (
  bundleID INT NULL,
  name VARCHAR(45) NOT NULL,
  description TEXT NOT NULL,
  price INT NOT NULL,
  PRIMARY KEY (bundleID))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table peduli_panti.cart
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS peduli_panti.cart (
  userID INT NOT NULL,
  productID INT NULL,
  bundleID INT NULL,
  quantity INT NOT NULL,
  INDEX productID_idx (productID ASC) VISIBLE,
  INDEX bundleID_idx (bundleID ASC) VISIBLE,
  CONSTRAINT userID
    FOREIGN KEY (userID)
    REFERENCES peduli_panti.user (userID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT productID
    FOREIGN KEY (productID)
    REFERENCES peduli_panti.product (productID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT bundleID
    FOREIGN KEY (bundleID)
    REFERENCES peduli_panti.bundle (bundleID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table peduli_panti.panti_detail
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS peduli_panti.panti_detail (
  pantiID INT NOT NULL,
  organizer VARCHAR(45) NOT NULL,
  name VARCHAR(45) NOT NULL,
  address TEXT NOT NULL,
  child_number INT NOT NULL,
  founding_date DATE NOT NULL,
  donation_total INT NOT NULL,
  value VARCHAR(45) NOT NULL,
  description TEXT NULL,
  image BLOB NULL,
  PRIMARY KEY (pantiID))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table peduli_panti.transaction_detail
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS peduli_panti.transaction_detail (
  transactionID VARCHAR(45) NOT NULL,
  userID INT NOT NULL,
  productID INT NULL,
  bundleID INT NULL,
  date DATE NOT NULL,
  price_total INT NOT NULL,
  method VARCHAR(45) NOT NULL,
  time TIME NOT NULL,
  PRIMARY KEY (transactionID),
  INDEX userID_idx (userID ASC) VISIBLE,
  INDEX productID_idx (productID ASC) VISIBLE,
  INDEX bundleID_idx (bundleID ASC) VISIBLE,
  CONSTRAINT userID
    FOREIGN KEY (userID)
    REFERENCES peduli_panti.user (userID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT productID
    FOREIGN KEY (productID)
    REFERENCES peduli_panti.product (productID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT bundleID
    FOREIGN KEY (bundleID)
    REFERENCES peduli_panti.bundle (bundleID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table peduli_panti.history
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS peduli_panti.history (
  transactionID VARCHAR(45) NOT NULL,
  pantiID INT NOT NULL,
  status VARCHAR(45) NOT NULL,
  INDEX transactionID_idx (transactionID ASC) VISIBLE,
  INDEX pantiID_idx (pantiID ASC) VISIBLE,
  CONSTRAINT transactionID
    FOREIGN KEY (transactionID)
    REFERENCES peduli_panti.transaction_detail (transactionID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT pantiID
    FOREIGN KEY (pantiID)
    REFERENCES peduli_panti.panti_detail (pantiID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table peduli_panti.RAB
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS peduli_panti.RAB (
  RABID INT NOT NULL,
  pantiID INT NOT NULL,
  pdf BLOB NOT NULL,
  status VARCHAR(45) NOT NULL,
  PRIMARY KEY (RABID),
  INDEX pantiID_idx (pantiID ASC) VISIBLE,
  CONSTRAINT pantiID
    FOREIGN KEY (pantiID)
    REFERENCES peduli_panti.panti_detail (pantiID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table peduli_panti.bundle_detail
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS peduli_panti.bundle_detail (
  bundleID INT NOT NULL,
  productID INT NOT NULL,
  INDEX bundleID_idx (bundleID ASC) VISIBLE,
  INDEX productID_idx (productID ASC) VISIBLE,
  CONSTRAINT bundleID
    FOREIGN KEY (bundleID)
    REFERENCES peduli_panti.bundle (bundleID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT productID
    FOREIGN KEY (productID)
    REFERENCES peduli_panti.product (productID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table peduli_panti.request_list
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS peduli_panti.request_list (
  pantiID INT NOT NULL,
  productID INT NOT NULL,
  INDEX pantiID_idx (pantiID ASC) VISIBLE,
  INDEX productID_idx (productID ASC) VISIBLE,
  CONSTRAINT pantiID
    FOREIGN KEY (pantiID)
    REFERENCES peduli_panti.panti_detail (pantiID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT productID
    FOREIGN KEY (productID)
    REFERENCES peduli_panti.product (productID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;